### ISSUE TITLE
Sms Namespace

### ISSUE THREAD

**Issue by Almeonamy** [kraaden/smshelpers#1]
Hello. You use `Sms` as root namespace, but many projects use this word as class name. If this projects want to use SmsHelpers, thay shold use class `Sms` with full namespace name such as `new Model.Notifications.Messaging.Sms();` instead of `new Sms();`.
Can you rename your root namespace using more specifically words such as `SmsHelpers`?

**Comment by kraaden** [comment]
Hi Almeonamy,

I changed namespace to `Texting` and updated the nuget package.

**Comment by kraaden** [comment]
@Almeonamy Yes, I already updated the package couple of days ago.

**Comment by Almeonamy** [comment]
Yes, it was my mistake. Thank you.
