### ISSUE TITLE
two '\'' in GsmCharacters

### ISSUE THREAD

**Issue by sequim** [kraaden/smshelpers#4]
Hi Kraaden,

Thank you for add the double quote in GsmCharacters.  I'm wondering why there are two '\'' entries (i.e., single quote) in GsmCharacters.

**Comment by kraaden** [comment]
The duplicate character is removed now.

**Comment by alexthekid07** [comment]
Could the curly-apostrophe have been a casualty of this change?
https://github.com/kraaden/smshelpers/commit/0547c060912f47fc47d76d4851d9c65f3d74195a#commitcomment-34288042
