### ISSUE TITLE
GsmCharactersExtension

### ISSUE THREAD

**Issue by sequim** [kraaden/smshelpers#5]
I found ten extended characters in https://www.developershome.com/sms/gsmAlphabet.asp.  

According to https://support.fastsms.co.uk/knowledgebase/gsm-character-set/ , the length of Carriage return and £ are 2.  I don't know if the web page is correct.  If they are, please add them in  GsmCharactersExtension and remove them from GsmCharacters.  Thank you!

**Comment by kraaden** [comment]
I think both characters are regular (basic) GSM characters, at least according to wikipedia and sms length calculator:

https://en.wikipedia.org/wiki/GSM_03.38
https://messente.com/documentation/tools/sms-length-calculator

**Comment by sequim** [comment]
Case is closed!  Thank you! :)

**Comment by sequim** [comment]
Case closed.
